domain_path: C:\Users\liamb\GitHub\KBSCE-Plotter\Vitis\bare_minimum_risc-V\export\bare_minimum_risc-V\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
