domain_path: /home/maartenvk/Documents/vitis_workspaces/KBSCE-Plotter/Vitis/linux/export/linux/sw/standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
