# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/maartenvk/src/KBSCE-Plotter/Vivado/KBSCE-Plotter.srcs/sources_1/bd/RISC_V/ip/RISC_V_lmb_bram_0/RISC_V_lmb_bram_0.xci
# IP: The module: 'RISC_V_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maartenvk/src/KBSCE-Plotter/Vivado/KBSCE-Plotter.gen/sources_1/bd/RISC_V/ip/RISC_V_lmb_bram_0/RISC_V_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISC_V_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/maartenvk/src/KBSCE-Plotter/Vivado/KBSCE-Plotter.srcs/sources_1/bd/RISC_V/ip/RISC_V_lmb_bram_0/RISC_V_lmb_bram_0.xci
# IP: The module: 'RISC_V_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/maartenvk/src/KBSCE-Plotter/Vivado/KBSCE-Plotter.gen/sources_1/bd/RISC_V/ip/RISC_V_lmb_bram_0/RISC_V_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISC_V_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
