# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VHDL_Projects/Nexys-A7-100T-Master.xdc

# Block Designs: bd/RISC_V/RISC_V.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V || ORIG_REF_NAME==RISC_V} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_microblaze_riscv_0_0/RISC_V_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_microblaze_riscv_0_0 || ORIG_REF_NAME==RISC_V_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_dlmb_v10_0/RISC_V_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_dlmb_v10_0 || ORIG_REF_NAME==RISC_V_dlmb_v10_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_ilmb_v10_0/RISC_V_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_ilmb_v10_0 || ORIG_REF_NAME==RISC_V_ilmb_v10_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_dlmb_bram_if_cntlr_0/RISC_V_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==RISC_V_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_ilmb_bram_if_cntlr_0/RISC_V_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==RISC_V_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_lmb_bram_0/RISC_V_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_lmb_bram_0 || ORIG_REF_NAME==RISC_V_lmb_bram_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_mdm_1_0/RISC_V_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_mdm_1_0 || ORIG_REF_NAME==RISC_V_mdm_1_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_clk_wiz_1_0/RISC_V_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_clk_wiz_1_0 || ORIG_REF_NAME==RISC_V_clk_wiz_1_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_rst_clk_wiz_1_100M_0/RISC_V_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==RISC_V_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_axi_gpio_0_0/RISC_V_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_axi_gpio_0_0 || ORIG_REF_NAME==RISC_V_axi_gpio_0_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_axi_gpio_1_0/RISC_V_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_axi_gpio_1_0 || ORIG_REF_NAME==RISC_V_axi_gpio_1_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_axi_uartlite_0_0/RISC_V_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_axi_uartlite_0_0 || ORIG_REF_NAME==RISC_V_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_axi_smc_0/RISC_V_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_axi_smc_0 || ORIG_REF_NAME==RISC_V_axi_smc_0} -quiet] -quiet

# IP: bd/RISC_V/ip/RISC_V_reset_inv_0_0/RISC_V_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RISC_V_reset_inv_0_0 || ORIG_REF_NAME==RISC_V_reset_inv_0_0} -quiet] -quiet

# XDC: c:/Users/liamb/GitHub/KBSCE-Plotter/KBSCE-Plotter.gen/sources_1/bd/RISC_V/RISC_V_ooc.xdc
